CmdOnOffOderList = {

	"/notrade", 
	"/noshift", 
	"/noctrl", 
	"/skillfail", 
	"/notalkmsg", 
	"/notalkmsg2", 
	"/showname", 
	"/fog", 
	"/aura", 
	"/window", 
	"/miss", 
	"/q1", 
	"/q2", 
	"/effect", 
	"/bgm", 
	"/sound", 
	"/loginout", 
	"/shopping", 
	"/stateinfo", 
	"/snap", 
	"/itemsnap", 
	"/skillsnap", 
	"/hoai", 
	"/merai", 
	"/camera", 
	"/btg"
}
CmdOnOffList = {

	["/battlemode"] = 1,
	["/notrade"] = 1,
	["/noshift"] = 1,
	["/noctrl"] = 0,
	["/skillfail"] = 1,
	["/notalkmsg"] = 1,
	["/notalkmsg2"] = 1,
	["/showname"] = 1,
	["/fog"] = 1,
	["/aura"] = 1,
	["/window"] = 1,
	["/miss"] = 1,
	["/q1"] = 0,
	["/q2"] = 0,
	["/effect"] = 1,
	["/bgm"] = 1,
	["/sound"] = 1,
	["/loginout"] = 1,
	["/shopping"] = 1,
	["/stateinfo"] = 1,
	["/snap"] = 0,
	["/itemsnap"] = 0,
	["/skillsnap"] = 1,
	["/hoai"] = 0,
	["/merai"] = 0,
	["/camera"] = 0,
	["/btg"] = 1
}
CmdHelpList = {

	["/battlemode"] = "/battlemode : Q ~ O 를 누르면 스킬단축창2의 스킬들이 사용됩니다.",
	["/notrade"] = "/notrade : 거래신청을 자동으로 거절합니다 On Off",
	["/noshift"] = "/noshift : 쉬프트를 누르지않고 힐로 적을 공격할수있게됩니다 On Off",
	["/noctrl"] = "/noctrl : 콘트롤을 누르지않아도 자동공격이 됩니다. On Off",
	["/skillfail"] = "/skillfail : 빨간색의 스킬사용 실패 메세지를 표시하지 않습니다 On Off",
	["/notalkmsg"] = "/notalkmsg : 채팅내용을 채팅창에 표시하지 않습니다 On Off",
	["/notalkmsg2"] = "/notalkmsg2 : 채팅내용을 채팅창에 표시하지 않습니다 (길드말 포함) On Off",
	["/showname_on"] = "폰트가 정상적으로 바뀌었습니다 [이름표시방식 1]",
	["/showname_off"] = "폰트가 가늘게 바뀌면서 파티명도 표시됩니다 [이름표시방식 2]",
	["/fog"] = "/fog : FOG이펙트를 키거나 끌수있습니다 On Off",
	["/aura"] = "/aura : 오오라를 간략화 시킬수있습니다 On Off",
	["/window"] = "/window : 창 위치 이동시 다른 창과 달라붙는 속성이 들어갑니다 On Off",
	["/miss"] = "/miss : 미스표시 On Off",
	["/q1"] = "/quickspell  : 마우스 우클릭으로 F9에 저장한 스킬을 사용합니다 On Off",
	["/q2"] = "/quickspell2 : 마우스 WHEEL을 위,아래로 굴려서 F7과F8에 저장한 스킬을 사용합니다 On Off",
	["/effect"] = "/이펙트 : 이펙트 On Off",
	["/bgm"] = "/음악 : 배경음악 ON OFF",
	["/sound"] = "/효과음 : 효과음 On Off",
	["/loginout"] = "/loginout : 길드원과 친구들의 접속관련 메세지를 보여줍니다. On Off",
	["/shopping"] = "/shopping : 클릭 한번으로 상점을 열고 상점이름 오른쪽 클릭으로 상점을 닫습니다 On Off",
	["/stateinfo"] = "/stateinfo : 상태 아이콘에 대한 설명을 보여줍니다. On Off",
	["/snap"] = "/snap : 공격 대상의 근처에서 마우스 커서를 유도합니다. ON OFF",
	["/itemsnap"] = "/itemsnap : 아이템의 근처에서 마우스 커서를 유도합니다. ON OFF",
	["/skillsnap"] = "/skillsnap : 스킬 대상의 근처에서 마우스 커서를 유도합니다. ON OFF",
	["/hoai"] = "/hoai : 호문클루스의 사용자 인공지능을 사용합니다. ON OFF",
	["/merai"] = "/merai : 용병의 사용자 인공지능을 사용합니다. ON OFF",
	["/camera"] = "/camera : 카메라를 고정합니다. ON OFF",
	["/btg"] = "/btg : 기본 정보창 확장 옵션에서 전장 아이콘을 보여줍니다. ON OFF",

	["/taekwon"] = "TAEKWON RANK",
	["/munak"] = "TAIMING RANK",
	["/death"] = "DEATH KNIGHT RANK",
	["/collector"] = "COLLECTOR RANK",
	["/hi"] = "/hi 또는 /hi 문장 : 친구로 등록된 캐릭터들에게 인사를 합니다.",
	["/blacksmith"] = "/blacksmith : 블랙스미스의 상위 10위권 랭킹을 보여줍니다.",
	["/alchemist"] = "/alchemist : 알케미스트의 상위 10위권 랭킹을 보여줍니다.",
	["/help"] = "/h or /help: 명령어 일람",
	["/who"] = "/w or /who or /접속자 or /누구: 현재 접속자수 보기",
	["/sit"] = "/앉기 or /sit : 앉기. 앉아있을때 서기",
	["/stand"] = "/서기 or /stand : 서기. 서있을때 앉기",
	["/q"] = "/q : 채팅방 나가기",
	["/leave"] = "/탈퇴 or /leave : 파티 탈퇴",
	["/where"] = "/좌표 or /장소: 현재 위치 표시",
	["/memo"] = "워프 장소로 기억됨",
	["/chat"] = "/채팅방 or /chat : 채팅방 만들기창 띄우기",
	["/savechat"] = "/갈무리 or /savechat : 채팅 내용 파일로 저장하기",
	["/doridori"] = "/doridori : 연속해서 이 명령어를 쳐주면 캐릭터가 도리도리 ^^;;",
	["/bangbang"] = "/bingbing : 연속해서 이 명령어를 쳐주면 캐릭터가 빙글빙글 ^^;;",
	["/bingbing"] = "/bangbang : 연속해서 이 명령어를 쳐주면 캐릭터가 뱅글뱅글 ^^;;",
	["/ex"] = "귓말 리스트 창 여는법 : [Alt] + [H] 를 누르면 귓말 리스트 창이 열립니다.",
	["/inall"] = "모두에게 귓말 가능 상태가 됨",
	["/exall"] = "모두에게 귓말 거부 상태로 됨",
	["/pvpinfo"] = "/pvpinfo : 자신의 PVP 승패와 PVP 포인트를 알 수 있습니다.",
	["/hunting"] = "/hunting : 사냥 목록을 보여줍니다"
}
OptionInfoList = {

	["Window_XPos"] = -1,
	["Window_YPos"] = -1,
	["Trilinear"] = 0,
	["Bgm_Volume"] = 100,
	["Effect_Volume"] = 100,
	["AutoOpen1to1Window"] = 1,
	["AutoOpen1to1Window_Friend"] = 1,
	["PlaySound_Open1to1Window"] = 1,
	["Simplicity_SkillList"] = 0,
	["Show_SkillDescript"] = 0,
	["ChangeChatMode"] = 1,
	["LockMouse"] = 0,
	["ChannelCopID"] = 0,
	["Outdoor_ViewLatitude"] = -45,
	["Outdoor_ViewDistance"] = 300,
	["Indoor_ViewLatitude"] = -45,
	["Indoor_ViewDistance"] = 300,
	["SkinName"] = "<Basic Skin>"
}