NEED_SKILLLIST_FOR_JOB = {
	[0] = {
		{"NV_BASIC"; Pos = 0, MaxLv = 9, NeedSkillList = {}}, 
		{"NV_FIRSTAID"; Pos = 7, MaxLv = 1, NeedSkillList = {}}, 
		{"NV_TRICKDEAD"; Pos = 14, MaxLv = 1, NeedSkillList = {}}}, 
	[1] = {
		{"SM_SWORD"; Pos = 1, MaxLv = 10, NeedSkillList = {}}, 
		{"SM_RECOVERY"; Pos = 2, MaxLv = 10, NeedSkillList = {}}, 
		{"SM_BASH"; Pos = 3, MaxLv = 10, NeedSkillList = {}}, 
		{"SM_PROVOKE"; Pos = 4, MaxLv = 10, NeedSkillList = {}}, 
		{"SM_AUTOBERSERK"; Pos = 5, MaxLv = 1, NeedSkillList = {}}, 
		{"SM_MOVINGRECOVERY"; Pos = 6, MaxLv = 1, NeedSkillList = {}}, 
		{"SM_TWOHAND"; Pos = 8, MaxLv = 10, NeedSkillList = {1}}, 
		{"SM_MAGNUM"; Pos = 10, MaxLv = 10, NeedSkillList = {3}}, 
		{"SM_ENDURE"; Pos = 11, MaxLv = 10, NeedSkillList = {4}}, 
		{"SM_FATALBLOW"; Pos = 12, MaxLv = 1, NeedSkillList = {}}},
	[10] = {
		{"BS_IRON"; Pos = 0, MaxLv = 5, NeedSkillList = {}}, 
		{"BS_HILTBINDING"; Pos = 1, MaxLv = 1, NeedSkillList = {}}, 
		{"BS_SKINTEMPER"; Pos = 2, MaxLv = 5, NeedSkillList = {}}, 
		{"BS_HAMMERFALL"; Pos = 3, MaxLv = 5, NeedSkillList = {}}, 
		{"BS_DAGGER"; Pos = 5, MaxLv = 3, NeedSkillList = {}}, 
		{"BS_STEEL"; Pos = 7, MaxLv = 5, NeedSkillList = {0}}, 
		{"BS_ENCHANTEDSTONE"; Pos = 8, MaxLv = 5, NeedSkillList = {0}}, 
		{"BS_WEAPONRESEARCH"; Pos = 9, MaxLv = 10, NeedSkillList = {1}}, 
		{"BS_ADRENALINE"; Pos = 10, MaxLv = 5, NeedSkillList = {3}}, 
		{"BS_SPEAR"; Pos = 11, MaxLv = 3, NeedSkillList = {5}}, 
		{"BS_SWORD"; Pos = 12, MaxLv = 3, NeedSkillList = {5}}, 
		{"BS_KNUCKLE"; Pos = 13, MaxLv = 3, NeedSkillList = {5}}, 
		{"BS_FINDINGORE"; Pos = 14, MaxLv = 1, NeedSkillList = {1, 7}}, 
		{"BS_ORIDEOCON"; Pos = 15, MaxLv = 5, NeedSkillList = {8}}, 
		{"BS_REPAIRWEAPON"; Pos = 16, MaxLv = 1, NeedSkillList = {9}}, 
		{"BS_WEAPONPERFECT"; Pos = 17, MaxLv = 5, NeedSkillList = {9, 10}}, 
		{"BS_OVERTHRUST"; Pos = 18, MaxLv = 5, NeedSkillList = {10}}, 
		{"BS_TWOHANDSWORD"; Pos = 19, MaxLv = 3, NeedSkillList = {12}}, 
		{"BS_MACE"; Pos = 20, MaxLv = 3, NeedSkillList = {13}}, 
		{"BS_MAXIMIZE"; Pos = 24, MaxLv = 5, NeedSkillList = {17, 18}}, 
		{"BS_AXE"; Pos = 26, MaxLv = 3, NeedSkillList = {12}}, 
		{"BS_ADRENALINE2"; Pos = 31, MaxLv = 1, NeedSkillList = {}}, 
		{"BS_GREED"; Pos = 33, MaxLv = 1, NeedSkillList = {}}, 
		{"BS_UNFAIRLYTRICK"; Pos = 34, MaxLv = 1, NeedSkillList = {}}},	
	[11] = {
		{"HT_BEASTBANE"; Pos = 0, MaxLv = 10, NeedSkillList = {}},
		{"HT_SKIDTRAP"; Pos = 2, MaxLv = 5, NeedSkillList = {}},
		{"HT_LANDMINE"; Pos = 4, MaxLv = 5, NeedSkillList = {}},
		{"HT_POWER"; Pos = 6, MaxLv = 1, NeedSkillList = {}},
		{"HT_FALCON"; Pos = 7, MaxLv = 1, NeedSkillList = {0}},
		{"HT_FLASHER"; Pos = 9, MaxLv = 5, NeedSkillList = {2}},
		{"HT_ANKLESNARE"; Pos = 10, MaxLv = 5, NeedSkillList = {2}},
		{"HT_REMOVETRAP"; Pos = 11, MaxLv = 1, NeedSkillList = {4}},
		{"HT_PHANTASMIC"; Pos = 13, MaxLv = 1, NeedSkillList = {}},
		{"HT_BLITZBEAT"; Pos = 14, MaxLv = 5, NeedSkillList = {7}},
		{"HT_SANDMAN"; Pos = 15, MaxLv = 5, NeedSkillList = {9}},
		{"HT_FREEZINGTRAP"; Pos = 16, MaxLv = 5, NeedSkillList = {9}},
		{"HT_SHOCKWAVE"; Pos = 17, MaxLv = 5, NeedSkillList = {10}},
		{"HT_SPRINGTRAP"; Pos = 18, MaxLv = 5, NeedSkillList = {7, 11}},
		{"HT_DETECTING"; Pos = 19, MaxLv = 4, NeedSkillList = {7}},
		{"HT_STEELCROW"; Pos = 21, MaxLv = 10, NeedSkillList = {14}},
		{"HT_BLASTMINE"; Pos = 22, MaxLv = 5, NeedSkillList = {4, 15, 16}},
		{"HT_TALKIEBOX"; Pos = 24, MaxLv = 1, NeedSkillList = {11, 17}},
		{"HT_CLAYMORETRAP"; Pos = 29, MaxLv = 5, NeedSkillList = {17, 22}}},	
	[12] = {
		{"AS_RIGHT"; Pos = 0, MaxLv = 5, NeedSkillList = {}},
		{"AS_KATAR"; Pos = 1, MaxLv = 10, NeedSkillList = {}},
		{"AS_CLOAKING"; Pos = 2, MaxLv = 10, NeedSkillList = {}},
		{"AS_ENCHANTPOISON"; Pos = 3, MaxLv = 10, NeedSkillList = {}},
		{"AS_VENOMKNIFE"; Pos = 6, MaxLv = 1, NeedSkillList = {}},
		{"AS_LEFT"; Pos = 7, MaxLv = 5, NeedSkillList = {0}},
		{"AS_SONICBLOW"; Pos = 8, MaxLv = 10, NeedSkillList = {1}},
		{"AS_VENOMDUST"; Pos = 10, MaxLv = 10, NeedSkillList = {3}},
		{"AS_POISONREACT"; Pos = 11, MaxLv = 10, NeedSkillList = {3}},
		{"AS_SONICACCEL"; Pos = 13, MaxLv = 1, NeedSkillList = {}},
		{"AS_GRIMTOOTH"; Pos = 15, MaxLv = 5, NeedSkillList = {2, 8}},
		{"AS_SPLASHER"; Pos = 17, MaxLv = 10, NeedSkillList = {10, 11}}},
	[14] = {
		{"CR_TRUST"; Pos = 0, MaxLv = 10, NeedSkillList = {}},
		{"CR_AUTOGUARD"; Pos = 2, MaxLv = 10, NeedSkillList = {}},
		{"KN_SPEARMASTERY"; Pos = 4, MaxLv = 10, NeedSkillList = {}},
		{"KN_RIDING"; Pos = 5, MaxLv = 1, NeedSkillList = {}},
		{"CR_SHRINK"; Pos = 6, MaxLv = 1, NeedSkillList = {}},
		{"AL_CURE"; Pos = 7, MaxLv = 1, NeedSkillList = {0}},
		{"CR_HOLYCROSS"; Pos = 8, MaxLv = 10, NeedSkillList = {0}},
		{"CR_SHIELDCHARGE"; Pos = 9, MaxLv = 5, NeedSkillList = {2}},
		{"CR_SPEARQUICKEN"; Pos = 11, MaxLv = 10, NeedSkillList = {4}},
		{"KN_CAVALIERMASTERY"; Pos = 12, MaxLv = 5, NeedSkillList = {5}},
		{"AL_DP"; Pos = 14, MaxLv = 10, NeedSkillList = {7}},
		{"CR_GRANDCROSS"; Pos = 15, MaxLv = 10, NeedSkillList = {0, 8}},
		{"CR_SHIELDBOOMERANG"; Pos = 16, MaxLv = 5, NeedSkillList = {9}},
		{"AL_DEMONBANE"; Pos = 21, MaxLv = 10, NeedSkillList = {14}},
		{"CR_REFLECTSHIELD"; Pos = 23, MaxLv = 10, NeedSkillList = {16}},
		{"CR_DEFENDER"; Pos = 24, MaxLv = 5, NeedSkillList = {16}},
		{"AL_HEAL"; Pos = 28, MaxLv = 10, NeedSkillList = {0, 21}},
		{"CR_DEVOTION"; Pos = 29, MaxLv = 5, NeedSkillList = {15, 23}},
		{"CR_PROVIDENCE"; Pos = 35, MaxLv = 5, NeedSkillList = {14, 28}}},
	[15] = {
		{"MO_IRONHAND"; Pos = 0, MaxLv = 10, NeedSkillList = {}},
		{"MO_CALLSPIRITS"; Pos = 1, MaxLv = 5, NeedSkillList = {0}},
		{"MO_DODGE"; Pos = 2, MaxLv = 10, NeedSkillList = {0, 1}},
		{"MO_TRIPLEATTACK"; Pos = 3, MaxLv = 10, NeedSkillList = {2}},
		{"MO_KITRANSLATION"; Pos = 5, MaxLv = 1, NeedSkillList = {}},
		{"MO_ABSORBSPIRITS"; Pos = 7, MaxLv = 1, NeedSkillList = {1}},
		{"MO_INVESTIGATE"; Pos = 8, MaxLv = 5, NeedSkillList = {1}},
		{"MO_BLADESTOP"; Pos = 9, MaxLv = 5, NeedSkillList = {2}},
		{"MO_CHAINCOMBO"; Pos = 10, MaxLv = 5, NeedSkillList = {3}},
		{"MO_BALKYOUNG"; Pos = 12, MaxLv = 1, NeedSkillList = {}},
		{"MO_EXPLOSIONSPIRITS"; Pos = 14, MaxLv = 5, NeedSkillList = {7}},
		{"MO_FINGEROFFENSIVE"; Pos = 15, MaxLv = 5, NeedSkillList = {8}},
		{"MO_SPIRITSRECOVERY"; Pos = 16, MaxLv = 5, NeedSkillList = {9}},
		{"MO_COMBOFINISH"; Pos = 17, MaxLv = 5, NeedSkillList = {10}},
		{"MO_EXTREMITYFIST"; Pos = 22, MaxLv = 5, NeedSkillList = {14, 15}},
		{"MO_STEELBODY"; Pos = 24, MaxLv = 5, NeedSkillList = {17}},
		{"MO_BODYRELOCATION"; Pos = 30, MaxLv = 1, NeedSkillList = {16, 22, 24}}},
	[16] = {
		{"SA_ADVANCEDBOOK"; Pos = 0, MaxLv = 10, NeedSkillList = {}},
		{"WZ_ESTIMATION"; Pos = 1, MaxLv = 1, NeedSkillList = {}},
		{"SA_ELEMENTWATER"; Pos = 2, MaxLv = 1, NeedSkillList = {}},
		{"SA_ELEMENTWIND"; Pos = 3, MaxLv = 1, NeedSkillList = {}},
		{"SA_ELEMENTGROUND"; Pos = 4, MaxLv = 1, NeedSkillList = {}},
		{"SA_ELEMENTFIRE"; Pos = 5, MaxLv = 1, NeedSkillList = {}},
		{"SA_CREATECON"; Pos = 6, MaxLv = 1, NeedSkillList = {}},
		{"SA_DRAGONOLOGY"; Pos = 7, MaxLv = 5, NeedSkillList = {0}},
		{"SA_SEISMICWEAPON"; Pos = 8, MaxLv = 5, NeedSkillList = {0}},
		{"SA_CASTCANCEL"; Pos = 9, MaxLv = 5, NeedSkillList = {0}},
		{"SA_MAGICROD"; Pos = 10, MaxLv = 5, NeedSkillList = {0}},
		{"SA_FROSTWEAPON"; Pos = 11, MaxLv = 5, NeedSkillList = {0}},
		{"SA_LIGHTNINGLOADER"; Pos = 12, MaxLv = 5, NeedSkillList = {0}},
		{"SA_FLAMELAUNCHER"; Pos = 13, MaxLv = 5, NeedSkillList = {0}},
		{"WZ_EARTHSPIKE"; Pos = 15, MaxLv = 5, NeedSkillList = {8}},
		{"SA_FREECAST"; Pos = 16, MaxLv = 10, NeedSkillList = {9}},
		{"SA_SPELLBREAKER"; Pos = 17, MaxLv = 5, NeedSkillList = {10}},
		{"SA_DELUGE"; Pos = 18, MaxLv = 5, NeedSkillList = {11}},
		{"SA_VIOLENTGALE"; Pos = 19, MaxLv = 5, NeedSkillList = {12}},
		{"SA_VOLCANO"; Pos = 20, MaxLv = 5, NeedSkillList = {13}},
		{"WZ_HEAVENDRIVE"; Pos = 22, MaxLv = 5, NeedSkillList = {15}},
		{"SA_AUTOSPELL"; Pos = 23, MaxLv = 10, NeedSkillList = {16}},
		{"SA_DISPELL"; Pos = 24, MaxLv = 5, NeedSkillList = {17}},
		{"SA_LANDPROTECTOR"; Pos = 26, MaxLv = 5, NeedSkillList = {18, 19, 20}},
		{"SA_ABRACADABRA"; Pos = 33, MaxLv = 10, NeedSkillList = {23, 24, 26}}},
	[17] = {
		{"AC_VULTURE"; Pos = 0, MaxLv = 10, NeedSkillList = {}},
		{"RG_TUNNELDRIVE"; Pos = 1, MaxLv = 5, NeedSkillList = {}},
		{"RG_SNATCHER"; Pos = 2, MaxLv = 10, NeedSkillList = {}},
		{"RG_STRIPHELM"; Pos = 3, MaxLv = 5, NeedSkillList = {9}},
		{"SM_SWORD"; Pos = 4, MaxLv = 10, NeedSkillList = {}},
		{"RG_CLOSECONFINE"; Pos = 5, MaxLv = 1, NeedSkillList = {}},
		{"AC_DOUBLE"; Pos = 7, MaxLv = 10, NeedSkillList = {0}},
		{"RG_STEALCOIN"; Pos = 9, MaxLv = 10, NeedSkillList = {2}},
		{"RG_STRIPSHIELD"; Pos = 10, MaxLv = 5, NeedSkillList = {3}},
		{"RG_GANGSTER"; Pos = 11, MaxLv = 1, NeedSkillList = {10}},
		{"HT_REMOVETRAP"; Pos = 14, MaxLv = 1, NeedSkillList = {7}},
		{"RG_BACKSTAP"; Pos = 16, MaxLv = 10, NeedSkillList = {9}},
		{"RG_STRIPARMOR"; Pos = 17, MaxLv = 5, NeedSkillList = {10}},
		{"RG_CLEANER"; Pos = 18, MaxLv = 1, NeedSkillList = {11}},
		{"RG_COMPULSION"; Pos = 19, MaxLv = 5, NeedSkillList = {11}},
		{"RG_RAID"; Pos = 22, MaxLv = 5, NeedSkillList = {1, 16}},
		{"RG_STRIPWEAPON"; Pos = 24, MaxLv = 5, NeedSkillList = {17}},
		{"RG_FLAGGRAFFITI"; Pos = 25, MaxLv = 5, NeedSkillList = {18}},
		{"RG_INTIMIDATE"; Pos = 29, MaxLv = 5, NeedSkillList = {16, 22}},
		{"RG_GRAFFITI"; Pos = 32, MaxLv = 1, NeedSkillList = {25}},
		{"RG_PLAGIARISM"; Pos = 36, MaxLv = 10, NeedSkillList = {29}}},
	[18] = {
		{"AM_LEARNINGPOTION"; Pos = 0, MaxLv = 10, NeedSkillList = {}},
		{"AM_SPHEREMINE"; Pos = 1, MaxLv = 5, NeedSkillList = {7}},
		{"AM_AXEMASTERY"; Pos = 2, MaxLv = 10, NeedSkillList = {}},
		{"AM_CP_HELM"; Pos = 3, MaxLv = 5, NeedSkillList = {7}},
		{"AM_BIOETHICS"; Pos = 4, MaxLv = 1, NeedSkillList = {}},
		{"AM_TWILIGHT1"; Pos = 6, MaxLv = 1, NeedSkillList = {7}},
		{"AM_PHARMACY"; Pos = 7, MaxLv = 10, NeedSkillList = {0}},
		{"AM_POTIONPITCHER"; Pos = 8, MaxLv = 5, NeedSkillList = {7}},
		{"AM_CP_SHIELD"; Pos = 10, MaxLv = 5, NeedSkillList = {3}},
		{"AM_REST"; Pos = 11, MaxLv = 1, NeedSkillList = {4}},
		{"AM_BERSERKPITCHER"; Pos = 12, MaxLv = 1, NeedSkillList = {}},
		{"AM_TWILIGHT2"; Pos = 13, MaxLv = 1, NeedSkillList = {7}},
		{"AM_DEMONSTRATION"; Pos = 15, MaxLv = 5, NeedSkillList = {7}},
		{"AM_CP_ARMOR"; Pos = 17, MaxLv = 5, NeedSkillList = {10}},
		{"AM_CALLHOMUN"; Pos = 18, MaxLv = 1, NeedSkillList = {11}},
		{"AM_TWILIGHT3"; Pos = 20, MaxLv = 1, NeedSkillList = {7}},
		{"AM_ACIDTERROR"; Pos = 22, MaxLv = 5, NeedSkillList = {7}},
		{"AM_CP_WEAPON"; Pos = 24, MaxLv = 5, NeedSkillList = {17}},
		{"AM_RESURRECTHOMUN"; Pos = 25, MaxLv = 5, NeedSkillList = {18}},
		{"AM_CANNIBALIZE"; Pos = 29, MaxLv = 5, NeedSkillList = {7}}},
	[19] = {
		{"BD_ADAPTATION"; Pos = 0, MaxLv = 1, NeedSkillList = {}},
		{"BA_MUSICALLESSON"; Pos = 1, MaxLv = 10, NeedSkillList = {}},
		{"BA_DISSONANCE"; Pos = 3, MaxLv = 5, NeedSkillList = {0, 1}},
		{"BA_PANGVOICE"; Pos = 5, MaxLv = 1, NeedSkillList = {}},
		{"BD_ENCORE"; Pos = 7, MaxLv = 1, NeedSkillList = {0}},
		{"BA_MUSICALSTRIKE"; Pos = 8, MaxLv = 5, NeedSkillList = {1}},
		{"BA_WHISTLE"; Pos = 9, MaxLv = 10, NeedSkillList = {3}},
		{"BA_ASSASSINCROSS"; Pos = 10, MaxLv = 10, NeedSkillList = {3}},
		{"BA_POEMBRAGI"; Pos = 11, MaxLv = 10, NeedSkillList = {3}},
		{"BA_APPLEIDUN"; Pos = 12, MaxLv = 10, NeedSkillList = {3}},
		{"BA_FROSTJOKE"; Pos = 14, MaxLv = 5, NeedSkillList = {7}},
		{"BD_LULLABY"; Pos = 16, MaxLv = 1, NeedSkillList = {9}},
		{"BD_ROKISWEIL"; Pos = 17, MaxLv = 1, NeedSkillList = {10}},
		{"BD_SIEGFRIED"; Pos = 18, MaxLv = 5, NeedSkillList = {11}},
		{"BD_DRUMBATTLEFIELD"; Pos = 19, MaxLv = 5, NeedSkillList = {12}},
		{"BD_INTOABYSS"; Pos = 23, MaxLv = 1, NeedSkillList = {16}},
		{"BD_ETERNALCHAOS"; Pos = 24, MaxLv = 1, NeedSkillList = {17}},
		{"BD_RICHMANKIM"; Pos = 25, MaxLv = 5, NeedSkillList = {18}},
		{"BD_RINGNIBELUNGEN"; Pos = 26, MaxLv = 5, NeedSkillList = {19}}},
	[2] = {
		{"MG_STONECURSE"; Pos = 1, MaxLv = 10, NeedSkillList = {}},
		{"MG_COLDBOLT"; Pos = 2, MaxLv = 10, NeedSkillList = {}},
		{"MG_LIGHTNINGBOLT"; Pos = 3, MaxLv = 10, NeedSkillList = {}},
		{"MG_NAPALMBEAT"; Pos = 4, MaxLv = 10, NeedSkillList = {}},
		{"MG_FIREBOLT"; Pos = 5, MaxLv = 10, NeedSkillList = {}},
		{"MG_SIGHT"; Pos = 6, MaxLv = 1, NeedSkillList = {}},
		{"MG_SRECOVERY"; Pos = 8, MaxLv = 10, NeedSkillList = {}},
		{"MG_FROSTDIVER"; Pos = 9, MaxLv = 10, NeedSkillList = {2}},
		{"MG_THUNDERSTORM"; Pos = 10, MaxLv = 10, NeedSkillList = {3}},
		{"MG_SOULSTRIKE"; Pos = 11, MaxLv = 10, NeedSkillList = {4}},
		{"MG_FIREBALL"; Pos = 12, MaxLv = 10, NeedSkillList = {5}},
		{"MG_ENERGYCOAT"; Pos = 13, MaxLv = 1, NeedSkillList = {}},
		{"MG_SAFETYWALL"; Pos = 18, MaxLv = 10, NeedSkillList = {4, 11}},
		{"MG_FIREWALL"; Pos = 19, MaxLv = 10, NeedSkillList = {6, 12}}},
	[20] = {
		{"BD_ADAPTATION"; Pos = 0, MaxLv = 1, NeedSkillList = {}},
		{"DC_DANCINGLESSON"; Pos = 1, MaxLv = 10, NeedSkillList = {}},
		{"DC_UGLYDANCE"; Pos = 3, MaxLv = 5, NeedSkillList = {0, 1}},
		{"DC_WINKCHARM"; Pos = 5, MaxLv = 1, NeedSkillList = {}},
		{"BD_ENCORE"; Pos = 7, MaxLv = 1, NeedSkillList = {0}},
		{"DC_THROWARROW"; Pos = 8, MaxLv = 5, NeedSkillList = {1}},
		{"DC_HUMMING"; Pos = 9, MaxLv = 10, NeedSkillList = {3}},
		{"DC_DONTFORGETME"; Pos = 10, MaxLv = 10, NeedSkillList = {3}},
		{"DC_FORTUNEKISS"; Pos = 11, MaxLv = 10, NeedSkillList = {3}},
		{"DC_SERVICEFORYOU"; Pos = 12, MaxLv = 10, NeedSkillList = {3}},
		{"DC_SCREAM"; Pos = 14, MaxLv = 5, NeedSkillList = {7}},
		{"BD_LULLABY"; Pos = 16, MaxLv = 1, NeedSkillList = {9}},
		{"BD_ROKISWEIL"; Pos = 17, MaxLv = 1, NeedSkillList = {10}},
		{"BD_SIEGFRIED"; Pos = 18, MaxLv = 5, NeedSkillList = {11}},
		{"BD_DRUMBATTLEFIELD"; Pos = 19, MaxLv = 5, NeedSkillList = {12}},
		{"BD_INTOABYSS"; Pos = 23, MaxLv = 1, NeedSkillList = {16}},
		{"BD_ETERNALCHAOS"; Pos = 24, MaxLv = 1, NeedSkillList = {17}},
		{"BD_RICHMANKIM"; Pos = 25, MaxLv = 5, NeedSkillList = {18}},
		{"BD_RINGNIBELUNGEN"; Pos = 26, MaxLv = 5, NeedSkillList = {19}}},
	[23] = {
		{"SM_SWORD"; Pos = 1, MaxLv = 10, NeedSkillList = {}},
		{"SM_BASH"; Pos = 2, MaxLv = 10, NeedSkillList = {}},
		{"SM_PROVOKE"; Pos = 3, MaxLv = 10, NeedSkillList = {}},
		{"TF_DOUBLE"; Pos = 4, MaxLv = 10, NeedSkillList = {}},
		{"TF_STEAL"; Pos = 5, MaxLv = 10, NeedSkillList = {}},
		{"TF_POISON"; Pos = 6, MaxLv = 10, NeedSkillList = {}},
		{"SM_RECOVERY"; Pos = 8, MaxLv = 10, NeedSkillList = {}},
		{"SM_MAGNUM"; Pos = 9, MaxLv = 10, NeedSkillList = {2}},
		{"SM_ENDURE"; Pos = 10, MaxLv = 10, NeedSkillList = {3}},
		{"TF_MISS"; Pos = 11, MaxLv = 10, NeedSkillList = {}},
		{"TF_HIDING"; Pos = 12, MaxLv = 10, NeedSkillList = {5}},
		{"TF_DETOXIFY"; Pos = 13, MaxLv = 1, NeedSkillList = {6}},
		{"MG_STONECURSE"; Pos = 15, MaxLv = 10, NeedSkillList = {}},
		{"MG_COLDBOLT"; Pos = 16, MaxLv = 10, NeedSkillList = {}},
		{"MG_LIGHTNINGBOLT"; Pos = 17, MaxLv = 10, NeedSkillList = {}},
		{"MG_NAPALMBEAT"; Pos = 18, MaxLv = 10, NeedSkillList = {}},
		{"MG_FIREBOLT"; Pos = 19, MaxLv = 10, NeedSkillList = {}},
		{"MG_SIGHT"; Pos = 20, MaxLv = 1, NeedSkillList = {}},
		{"MG_SRECOVERY"; Pos = 22, MaxLv = 10, NeedSkillList = {}},
		{"MG_FROSTDIVER"; Pos = 23, MaxLv = 10, NeedSkillList = {16}},
		{"MG_THUNDERSTORM"; Pos = 24, MaxLv = 10, NeedSkillList = {17}},
		{"MG_SOULSTRIKE"; Pos = 25, MaxLv = 10, NeedSkillList = {18}},
		{"MG_FIREBALL"; Pos = 26, MaxLv = 10, NeedSkillList = {19}},
		{"AL_RUWACH"; Pos = 28, MaxLv = 1, NeedSkillList = {}},
		{"AL_HEAL"; Pos = 29, MaxLv = 10, NeedSkillList = {}},
		{"AL_HOLYWATER"; Pos = 30, MaxLv = 1, NeedSkillList = {}},
		{"AL_DP"; Pos = 31, MaxLv = 10, NeedSkillList = {}},
		{"MG_SAFETYWALL"; Pos = 32, MaxLv = 10, NeedSkillList = {18, 25}},
		{"MG_FIREWALL"; Pos = 33, MaxLv = 10, NeedSkillList = {26}},
		{"AC_OWL"; Pos = 34, MaxLv = 10, NeedSkillList = {}},
		{"AL_TELEPORT"; Pos = 35, MaxLv = 2, NeedSkillList = {28}},
		{"AL_CURE"; Pos = 36, MaxLv = 1, NeedSkillList = {29}},
		{"AL_INCAGI"; Pos = 37, MaxLv = 10, NeedSkillList = {29}},
		{"AL_BLESSING"; Pos = 38, MaxLv = 10, NeedSkillList = {31}},
		{"AL_DEMONBANE"; Pos = 39, MaxLv = 10, NeedSkillList = {31}},
		{"AL_ANGELUS"; Pos = 40, MaxLv = 10, NeedSkillList = {31}},
		{"AC_VULTURE"; Pos = 41, MaxLv = 10, NeedSkillList = {34}},
		{"AL_WARP"; Pos = 42, MaxLv = 4, NeedSkillList = {35}},
		{"MC_INCCARRY"; Pos = 43, MaxLv = 10, NeedSkillList = {}},
		{"AL_DECAGI"; Pos = 44, MaxLv = 10, NeedSkillList = {37}},
		{"MC_IDENTIFY"; Pos = 45, MaxLv = 1, NeedSkillList = {}},
		{"AL_CRUCIS"; Pos = 46, MaxLv = 10, NeedSkillList = {39}},
		{"MC_MAMMONITE"; Pos = 47, MaxLv = 10, NeedSkillList = {}},
		{"AC_CONCENTRATION"; Pos = 48, MaxLv = 10, NeedSkillList = {41}},
		{"AL_PNEUMA"; Pos = 49, MaxLv = 1, NeedSkillList = {42}},
		{"MC_DISCOUNT"; Pos = 50, MaxLv = 10, NeedSkillList = {43}},
		{"MC_OVERCHARGE"; Pos = 51, MaxLv = 10, NeedSkillList = {50}},
		{"MC_PUSHCART"; Pos = 52, MaxLv = 10, NeedSkillList = {43}},
		{"MC_VENDING"; Pos = 53, MaxLv = 10, NeedSkillList = {52}}},
	[24] = {
		{"GS_GLITTERING"; Pos = 1, MaxLv = 5, NeedSkillList = {}},
		{"GS_MAGICALBULLET"; Pos = 2, MaxLv = 1, NeedSkillList = {1}},
		{"GS_SINGLEACTION"; Pos = 3, MaxLv = 10, NeedSkillList = {}},
		{"GS_SNAKEEYE"; Pos = 6, MaxLv = 10, NeedSkillList = {}},
		{"GS_FLING"; Pos = 8, MaxLv = 1, NeedSkillList = {1}},
		{"GS_CRACKER"; Pos = 9, MaxLv = 1, NeedSkillList = {1}},
		{"GS_CHAINACTION"; Pos = 10, MaxLv = 10, NeedSkillList = {3}},
		{"GS_TRACKING"; Pos = 11, MaxLv = 10, NeedSkillList = {3}},
		{"GS_DUST"; Pos = 12, MaxLv = 10, NeedSkillList = {3}},
		{"GS_INCREASING"; Pos = 13, MaxLv = 1, NeedSkillList = {1, 6}},
		{"GS_TRIPLEACTION"; Pos = 15, MaxLv = 1, NeedSkillList = {1, 10}},
		{"GS_DISARM"; Pos = 16, MaxLv = 5, NeedSkillList = {11}},
		{"GS_RAPIDSHOWER"; Pos = 17, MaxLv = 10, NeedSkillList = {10}},
		{"GS_PIERCINGSHOT"; Pos = 18, MaxLv = 5, NeedSkillList = {11}},
		{"GS_FULLBUSTER"; Pos = 19, MaxLv = 10, NeedSkillList = {12}},
		{"GS_ADJUSTMENT"; Pos = 23, MaxLv = 1, NeedSkillList = {1, 16}},
		{"GS_DESPERADO"; Pos = 24, MaxLv = 10, NeedSkillList = {17}},
		{"GS_BULLSEYE"; Pos = 25, MaxLv = 1, NeedSkillList = {1, 11}},
		{"GS_SPREADATTACK"; Pos = 26, MaxLv = 10, NeedSkillList = {19}},
		{"GS_GATLINGFEVER"; Pos = 31, MaxLv = 10, NeedSkillList = {24}},
		{"GS_GROUNDDRIFT"; Pos = 33, MaxLv = 10, NeedSkillList = {26}},
		{"GS_MADNESSCANCEL"; Pos = 38, MaxLv = 1, NeedSkillList = {31}}},
	[25] = {
		{"NJ_TOBIDOUGU"; Pos = 1, MaxLv = 10, NeedSkillList = {}},
		{"NJ_TATAMIGAESHI"; Pos = 2, MaxLv = 5, NeedSkillList = {}},
		{"NJ_NINPOU"; Pos = 5, MaxLv = 10, NeedSkillList = {}},
		{"NJ_SYURIKEN"; Pos = 8, MaxLv = 10, NeedSkillList = {1}},
		{"NJ_SHADOWJUMP"; Pos = 9, MaxLv = 5, NeedSkillList = {2}},
		{"NJ_NEN"; Pos = 10, MaxLv = 5, NeedSkillList = {5}},
		{"NJ_KOUENKA"; Pos = 11, MaxLv = 10, NeedSkillList = {5}},
		{"NJ_HYOUSENSOU"; Pos = 12, MaxLv = 10, NeedSkillList = {5}},
		{"NJ_HUUJIN"; Pos = 13, MaxLv = 10, NeedSkillList = {5}},
		{"NJ_KUNAI"; Pos = 15, MaxLv = 5, NeedSkillList = {8}},
		{"NJ_KASUMIKIRI"; Pos = 16, MaxLv = 10, NeedSkillList = {9}},
		{"NJ_UTSUSEMI"; Pos = 17, MaxLv = 5, NeedSkillList = {9}},
		{"NJ_KAENSIN"; Pos = 18, MaxLv = 10, NeedSkillList = {11}},
		{"NJ_SUITON"; Pos = 19, MaxLv = 10, NeedSkillList = {12}},
		{"NJ_RAIGEKISAI"; Pos = 20, MaxLv = 5, NeedSkillList = {13}},
		{"NJ_HUUMA"; Pos = 22, MaxLv = 5, NeedSkillList = {15}},
		{"NJ_KIRIKAGE"; Pos = 23, MaxLv = 5, NeedSkillList = {16}},
		{"NJ_BAKUENRYU"; Pos = 25, MaxLv = 5, NeedSkillList = {18}},
		{"NJ_HYOUSYOURAKU"; Pos = 26, MaxLv = 5, NeedSkillList = {19}},
		{"NJ_KAMAITACHI"; Pos = 27, MaxLv = 5, NeedSkillList = {20}},
		{"NJ_ZENYNAGE"; Pos = 29, MaxLv = 10, NeedSkillList = {22}},
		{"NJ_BUNSINJYUTSU"; Pos = 30, MaxLv = 10, NeedSkillList = {10, 17, 23}},
		{"NJ_ISSEN"; Pos = 31, MaxLv = 10, NeedSkillList = {1, 10, 23}}},
	[3] = {
		{"AC_DOUBLE"; Pos = 2, MaxLv = 10, NeedSkillList = {}},
		{"AC_OWL"; Pos = 3, MaxLv = 10, NeedSkillList = {}},
		{"AC_CHARGEARROW"; Pos = 5, MaxLv = 1, NeedSkillList = {}},
		{"AC_SHOWER"; Pos = 9, MaxLv = 10, NeedSkillList = {2}},
		{"AC_VULTURE"; Pos = 10, MaxLv = 10, NeedSkillList = {3}},
		{"AC_MAKINGARROW"; Pos = 12, MaxLv = 1, NeedSkillList = {}},
		{"AC_CONCENTRATION"; Pos = 17, MaxLv = 10, NeedSkillList = {10}}},		
	[4] = {
		{"AL_RUWACH"; Pos = 1, MaxLv = 1, NeedSkillList = {}},
		{"AL_HEAL"; Pos = 2, MaxLv = 10, NeedSkillList = {}},
		{"AL_HOLYWATER"; Pos = 3, MaxLv = 1, NeedSkillList = {}},
		{"AL_DP"; Pos = 5, MaxLv = 10, NeedSkillList = {}},
		{"AL_HOLYLIGHT"; Pos = 6, MaxLv = 1, NeedSkillList = {}},
		{"AL_TELEPORT"; Pos = 8, MaxLv = 2, NeedSkillList = {1}},
		{"AL_CURE"; Pos = 9, MaxLv = 1, NeedSkillList = {2}},
		{"AL_INCAGI"; Pos = 10, MaxLv = 10, NeedSkillList = {2}},
		{"AL_BLESSING"; Pos = 11, MaxLv = 10, NeedSkillList = {5}},
		{"AL_DEMONBANE"; Pos = 12, MaxLv = 10, NeedSkillList = {5}},
		{"AL_ANGELUS"; Pos = 13, MaxLv = 10, NeedSkillList = {5}},
		{"AL_WARP"; Pos = 15, MaxLv = 4, NeedSkillList = {8}},
		{"AL_DECAGI"; Pos = 17, MaxLv = 10, NeedSkillList = {10}},
		{"AL_CRUCIS"; Pos = 19, MaxLv = 10, NeedSkillList = {12}},
		{"AL_PNEUMA"; Pos = 22, MaxLv = 1, NeedSkillList = {15}}},		
	[4008] = {
		{"LK_BERSERK"; Pos = 4, MaxLv = 1, NeedSkillList = {}},
		{"LK_TENSIONRELAX"; Pos = 5, MaxLv = 1, NeedSkillList = {}},
		{"LK_PARRYING"; Pos = 7, MaxLv = 10, NeedSkillList = {0}},
		{"LK_AURABLADE"; Pos = 11, MaxLv = 5, NeedSkillList = {}},
		{"LK_CONCENTRATION"; Pos = 12, MaxLv = 5, NeedSkillList = {2, 3}},
		{"LK_HEADCRUSH"; Pos = 19, MaxLv = 5, NeedSkillList = {2, 3}},
		{"LK_SPIRALPIERCE"; Pos = 25, MaxLv = 5, NeedSkillList = {10, 2, 3, 17}},
		{"LK_JOINTBEAT"; Pos = 26, MaxLv = 10, NeedSkillList = {3, 2, 9, 19}}},	
	[4009] = {
		{"HP_ASSUMPTIO"; Pos = 10, MaxLv = 5, NeedSkillList = {3, 5}},
		{"HP_BASILICA"; Pos = 17, MaxLv = 5, NeedSkillList = {3, 7}},
		{"HP_MANARECHARGE"; Pos = 22, MaxLv = 5, NeedSkillList = {15}},
		{"HP_MEDITATIO"; Pos = 19, MaxLv = 10, NeedSkillList = {3, 4, 13}}},
	[4010] = {
		{"HW_GANBANTEIN"; Pos = 7, MaxLv = 1, NeedSkillList = {0, 1}},
		{"HW_MAGICCRASHER"; Pos = 12, MaxLv = 1, NeedSkillList = {}},
		{"HW_SOULDRAIN"; Pos = 13, MaxLv = 10, NeedSkillList = {}},
		{"HW_NAPALMVULCAN"; Pos = 19, MaxLv = 5, NeedSkillList = {}},
		{"HW_MAGICPOWER"; Pos = 20, MaxLv = 10, NeedSkillList = {}},
		{"HW_GRAVITATION"; Pos = 24, MaxLv = 5, NeedSkillList = {17, 12, 20}}},
		-- {"WZ_FIREIVY"; Pos = 25, MaxLv = 1, NeedSkillList = {}}},
	[4011] = {
		{"WS_CARTBOOST"; Pos = 21, MaxLv = 1, NeedSkillList = {1}},
		{"WS_CARTTERMINATION"; Pos = 28, MaxLv = 10, NeedSkillList = {3, 21}},
		{"WS_MELTDOWN"; Pos = 22, MaxLv = 10, NeedSkillList = {9, 18, 2}},
		{"WS_OVERTHRUSTMAX"; Pos = 25, MaxLv = 5, NeedSkillList = {18}},
		{"WS_WEAPONREFINE"; Pos = 23, MaxLv = 10, NeedSkillList = {9}}},
	[4012] = {
		{"SN_FALCONASSAULT"; Pos = 28, MaxLv = 5, NeedSkillList = {14, 21}},
		{"SN_SHARPSHOOTING"; Pos = 5, MaxLv = 5, NeedSkillList = {}},
		{"SN_SIGHT"; Pos = 26, MaxLv = 10, NeedSkillList = {7}},
		{"SN_WINDWALK"; Pos = 12, MaxLv = 10, NeedSkillList = {}}},
	[4013] = {
		{"ASC_BREAKER"; Pos = 18, MaxLv = 10, NeedSkillList = {2, 3}},
		{"ASC_CDP"; Pos = 12, MaxLv = 1, NeedSkillList = {3}},
		{"ASC_EDP"; Pos = 19, MaxLv = 5, NeedSkillList = {12}},
		{"ASC_KATAR"; Pos = 9, MaxLv = 5, NeedSkillList = {1}},
		{"ASC_METEORASSAULT"; Pos = 25, MaxLv = 10, NeedSkillList = {0, 1, 8, 18}}},
	[4015] = {
		{"PA_PRESSURE"; Pos = 17, MaxLv = 5, NeedSkillList = {0, 9}},
		{"PA_SHIELDCHAIN"; Pos = 25, MaxLv = 5, NeedSkillList = {16}},
		{"PA_GOSPEL"; Pos = 30, MaxLv = 10, NeedSkillList = {0, 14, 21}},
		{"PA_SACRIFICE"; Pos = 36, MaxLv = 5, NeedSkillList = {29}}},
	[4016] = {
		{"CH_PALMSTRIKE"; Pos = 11, MaxLv = 5, NeedSkillList = {0, 1}},
		{"CH_SOULCOLLECT"; Pos = 21, MaxLv = 1, NeedSkillList = {14}},
		{"CH_TIGERFIST"; Pos = 25, MaxLv = 5, NeedSkillList = {0, 1, 3, 17}},
		{"CH_CHAINCRUSH"; Pos = 32, MaxLv = 10, NeedSkillList = {0, 1, 25}}},
	[4017] = {
		{"PF_SPIDERWEB"; Pos = 14, MaxLv = 1, NeedSkillList = {7}},
		{"PF_SOULCHANGE"; Pos = 21, MaxLv = 1, NeedSkillList = {10, 17}},
		{"PF_FOGWALL"; Pos = 25, MaxLv = 1, NeedSkillList = {18, 19}},
		{"PF_HPCONVERSION"; Pos = 28, MaxLv = 5, NeedSkillList = {10}},
		{"PF_DOUBLECASTING"; Pos = 29, MaxLv = 5, NeedSkillList = {23}},
		{"PF_MEMORIZE"; Pos = 30, MaxLv = 1, NeedSkillList = {16, 23}},
		{"PF_SOULBURN"; Pos = 31, MaxLv = 5, NeedSkillList = {9, 10, 24}},
		{"PF_MINDBREAKER"; Pos = 32, MaxLv = 5, NeedSkillList = {31}}},	
	[4018] = {
		{"ST_CHASEWALK"; Pos = 8, MaxLv = 5, NeedSkillList = {1}},
		{"ST_FULLSTRIP"; Pos = 30, MaxLv = 5, NeedSkillList = {24}},
		{"ST_PRESERVE"; Pos = 38, MaxLv = 1, NeedSkillList = {36}},
		{"ST_REJECTSWORD"; Pos = 31, MaxLv = 5, NeedSkillList = {24}}},
	[4019] = {
		{"CR_CULTIVATION"; Pos = 5, MaxLv = 2, NeedSkillList = {}},
		{"CR_SLIMPITCHER"; Pos = 9, MaxLv = 10, NeedSkillList = {8}},
		{"CR_ACIDDEMONSTRATION"; Pos = 23, MaxLv = 10, NeedSkillList = {15, 22}},
		{"CR_FULLPROTECTION"; Pos = 31, MaxLv = 5, NeedSkillList = {3, 10, 17, 24}}},
	[4020] = {
		{"CG_ARROWVULCAN"; Pos = 29, MaxLv = 10, NeedSkillList = {8}},
		{"CG_MOONLIT"; Pos = 30, MaxLv = 5, NeedSkillList = {1}},
		{"CG_MARIONETTE"; Pos = 31, MaxLv = 1, NeedSkillList = {1,0}},
		{"CG_HERMODE"; Pos = 32, MaxLv = 5, NeedSkillList = {1}},
		{"CG_LONGINGFREEDOM"; Pos = 38, MaxLv = 5, NeedSkillList = {1, 3, 31}},
		{"CG_TAROTCARD"; Pos = 39, MaxLv = 5, NeedSkillList = {3}}},
	[4021] = {
		{"CG_ARROWVULCAN"; Pos = 29, MaxLv = 10, NeedSkillList = {8}},
		{"CG_MOONLIT"; Pos = 30, MaxLv = 5, NeedSkillList = {1}},
		{"CG_MARIONETTE"; Pos = 31, MaxLv = 1, NeedSkillList = {1}},
		{"CG_HERMODE"; Pos = 32, MaxLv = 5, NeedSkillList = {1}},
		{"CG_LONGINGFREEDOM"; Pos = 38, MaxLv = 5, NeedSkillList = {1, 3, 31}},
		{"CG_TAROTCARD"; Pos = 39, MaxLv = 5, NeedSkillList = {3}}},
	[4046] = {
		{"TK_RUN"; Pos = 1, MaxLv = 10, NeedSkillList = {}},
		{"TK_STORMKICK"; Pos = 2, MaxLv = 7, NeedSkillList = {}},
		{"TK_DOWNKICK"; Pos = 3, MaxLv = 7, NeedSkillList = {}},
		{"TK_TURNKICK"; Pos = 4, MaxLv = 7, NeedSkillList = {}},
		{"TK_COUNTER"; Pos = 5, MaxLv = 7, NeedSkillList = {}},
		{"TK_JUMPKICK"; Pos = 6, MaxLv = 7, NeedSkillList = {}},
		{"TK_HIGHJUMP"; Pos = 8, MaxLv = 5, NeedSkillList = {}},
		{"TK_READYSTORM"; Pos = 9, MaxLv = 1, NeedSkillList = {2}},
		{"TK_READYDOWN"; Pos = 10, MaxLv = 1, NeedSkillList = {3}},
		{"TK_READYTURN"; Pos = 11, MaxLv = 1, NeedSkillList = {4}},
		{"TK_READYCOUNTER"; Pos = 12, MaxLv = 1, NeedSkillList = {5}},
		{"TK_DODGE"; Pos = 13, MaxLv = 1, NeedSkillList = {6}},
		{"TK_HPTIME"; Pos = 16, MaxLv = 10, NeedSkillList = {}},
		{"TK_SPTIME"; Pos = 17, MaxLv = 10, NeedSkillList = {}},
		{"TK_POWER"; Pos = 18, MaxLv = 5, NeedSkillList = {}},
		{"TK_SEVENWIND"; Pos = 24, MaxLv = 7, NeedSkillList = {16, 17, 18}},
		{"TK_MISSION"; Pos = 25, MaxLv = 1, NeedSkillList = {18}}},
	[4047] = {
		{"SG_FEEL"; Pos = 0, MaxLv = 3, NeedSkillList = {}},
		{"SG_HATE"; Pos = 2, MaxLv = 3, NeedSkillList = {}},
		{"SG_DEVIL"; Pos = 4, MaxLv = 10, NeedSkillList = {}},
		{"SG_KNOWLEDGE"; Pos = 5, MaxLv = 10, NeedSkillList = {}},
		{"SG_SUN_WARM"; Pos = 7, MaxLv = 3, NeedSkillList = {0}},
		{"SG_SUN_COMFORT"; Pos = 8, MaxLv = 4, NeedSkillList = {0}},
		{"SG_SUN_ANGER"; Pos = 9, MaxLv = 3, NeedSkillList = {2}},
		{"SG_SUN_BLESS"; Pos = 10, MaxLv = 5, NeedSkillList = {0, 2}},
		{"SG_FRIEND"; Pos = 11, MaxLv = 3, NeedSkillList = {}},
		{"SG_FUSION"; Pos = 12, MaxLv = 1, NeedSkillList = {5}},
		{"SG_MOON_WARM"; Pos = 14, MaxLv = 3, NeedSkillList = {0}},
		{"SG_MOON_COMFORT"; Pos = 15, MaxLv = 4, NeedSkillList = {0}},
		{"SG_MOON_ANGER"; Pos = 16, MaxLv = 3, NeedSkillList = {2}},
		{"SG_MOON_BLESS"; Pos = 17, MaxLv = 5, NeedSkillList = {0, 2}},
		{"SG_STAR_WARM"; Pos = 21, MaxLv = 3, NeedSkillList = {0}},
		{"SG_STAR_COMFORT"; Pos = 22, MaxLv = 4, NeedSkillList = {0}},
		{"SG_STAR_ANGER"; Pos = 23, MaxLv = 3, NeedSkillList = {2}},
		{"SG_STAR_BLESS"; Pos = 24, MaxLv = 5, NeedSkillList = {0, 2}}},
	[4049] = {
		{"SL_ALCHEMIST"; Pos = 0, MaxLv = 5, NeedSkillList = {}},
		{"SL_STAR"; Pos = 1, MaxLv = 5, NeedSkillList = {}},
		{"SL_ASSASIN"; Pos = 2, MaxLv = 5, NeedSkillList = {}},
		{"SL_CRUSADER"; Pos = 3, MaxLv = 5, NeedSkillList = {}},
		{"SL_BARDDANCER"; Pos = 4, MaxLv = 5, NeedSkillList = {}},
		{"SL_SUPERNOVICE"; Pos = 5, MaxLv = 5, NeedSkillList = {}},
		{"SL_BLACKSMITH"; Pos = 7, MaxLv = 5, NeedSkillList = {0}},
		{"SL_SOULLINKER"; Pos = 8, MaxLv = 5, NeedSkillList = {1}},
		{"SL_ROGUE"; Pos = 9, MaxLv = 5, NeedSkillList = {2}},
		{"SL_KNIGHT"; Pos = 10, MaxLv = 5, NeedSkillList = {3}},
		{"SL_HUNTER"; Pos = 11, MaxLv = 5, NeedSkillList = {4}},
		{"SL_HIGH"; Pos = 12, MaxLv = 5, NeedSkillList = {5}},
		{"SL_MONK"; Pos = 14, MaxLv = 5, NeedSkillList = {}},
		{"SL_KAUPE"; Pos = 16, MaxLv = 3, NeedSkillList = {2, 9}},
		{"SL_SKE"; Pos = 17, MaxLv = 3, NeedSkillList = {10}},
		{"SL_SAGE"; Pos = 18, MaxLv = 5, NeedSkillList = {}},
		{"SL_KAINA"; Pos = 19, MaxLv = 7, NeedSkillList = {}},
		{"SL_PRIEST"; Pos = 21, MaxLv = 5, NeedSkillList = {14}},
		{"SL_SKA"; Pos = 22, MaxLv = 3, NeedSkillList = {14}},
		{"SL_WIZARD"; Pos = 25, MaxLv = 5, NeedSkillList = {18}},
		{"SL_KAITE"; Pos = 26, MaxLv = 7, NeedSkillList = {18, 25}},
		{"SL_KAAHI"; Pos = 28, MaxLv = 7, NeedSkillList = {3, 14, 21}},
		{"SL_KAIZEL"; Pos = 29, MaxLv = 7, NeedSkillList = {21}},
		{"SL_SWOO"; Pos = 30, MaxLv = 7, NeedSkillList = {21}},
		{"SL_STIN"; Pos = 31, MaxLv = 7, NeedSkillList = {25}},
		{"SL_STUN"; Pos = 32, MaxLv = 7, NeedSkillList = {25}},
		{"SL_SMA"; Pos = 33, MaxLv = 10, NeedSkillList = {31, 32}}},
	[4054] = {
		{"RK_RUNEMASTERY"; Pos = 1, MaxLv = 10, NeedSkillList = {}},
		{"RK_PHANTOMTHRUST"; Pos = 3, MaxLv = 5, NeedSkillList = {}},
		{"RK_DRAGONTRAINING"; Pos = 4, MaxLv = 5, NeedSkillList = {}},
		{"RK_ENCHANTBLADE"; Pos = 8, MaxLv = 5, NeedSkillList = {1}},
		{"RK_HUNDREDSPEAR"; Pos = 10, MaxLv = 10, NeedSkillList = {3}},
		{"RK_DRAGONHOWLING"; Pos = 11, MaxLv = 5, NeedSkillList = {4}},
		{"RK_DRAGONBREATH"; Pos = 12, MaxLv = 10, NeedSkillList = {4}},
		{"RK_DEATHBOUND"; Pos = 14, MaxLv = 10, NeedSkillList = {8}},
		{"RK_SONICWAVE"; Pos = 15, MaxLv = 5, NeedSkillList = {8}},
		{"RK_WINDCUTTER"; Pos = 16, MaxLv = 5, NeedSkillList = {8}},
		{"RK_IGNITIONBREAK"; Pos = 23, MaxLv = 5, NeedSkillList = {14, 15, 16}}},
	[4055] = {
		{"WL_MARSHOFABYSS"; Pos = 0, MaxLv = 5, NeedSkillList = {}},
		{"WL_RADIUS"; Pos = 1, MaxLv = 3, NeedSkillList = {}},
		{"WL_RELEASE"; Pos = 2, MaxLv = 2, NeedSkillList = {}},
		{"WL_SUMMONFB"; Pos = 3, MaxLv = 5, NeedSkillList = {}},
		{"WL_SUMMONWB"; Pos = 4, MaxLv = 5, NeedSkillList = {}},
		{"WL_SUMMONBL"; Pos = 5, MaxLv = 5, NeedSkillList = {}},
		{"WL_SUMMONSTONE"; Pos = 6, MaxLv = 5, NeedSkillList = {}},
		{"WL_FREEZE_SP"; Pos = 7, MaxLv = 5, NeedSkillList = {}},
		{"WL_DRAINLIFE"; Pos = 8, MaxLv = 5, NeedSkillList = {1}},
		{"WL_READING_SB"; Pos = 9, MaxLv = 1, NeedSkillList = {}},
		{"WL_CRIMSONROCK"; Pos = 10, MaxLv = 5, NeedSkillList = {3}},
		{"WL_FROSTMISTY"; Pos = 11, MaxLv = 5, NeedSkillList = {4}},
		{"WL_CHAINLIGHTNING"; Pos = 12, MaxLv = 5, NeedSkillList = {5}},
		{"WL_SIENNAEXECRATE"; Pos = 13, MaxLv = 5, NeedSkillList = {6}},
		{"WL_SOULEXPANSION"; Pos = 14, MaxLv = 5, NeedSkillList = {8}},
		{"WL_STASIS"; Pos = 15, MaxLv = 5, NeedSkillList = {8}},
		{"WL_HELLINFERNO"; Pos = 17, MaxLv = 5, NeedSkillList = {10}},
		{"WL_JACKFROST"; Pos = 18, MaxLv = 5, NeedSkillList = {11}},
		{"WL_EARTHSTRAIN"; Pos = 20, MaxLv = 5, NeedSkillList = {13}},
		{"WL_WHITEIMPRISON"; Pos = 21, MaxLv = 5, NeedSkillList = {14}},
		{"WL_COMET"; Pos = 25, MaxLv = 5, NeedSkillList = {17}},
		{"WL_RECOGNIZEDSPELL"; Pos = 30, MaxLv = 5, NeedSkillList = {2, 15, 21}},
		{"WL_TETRAVORTEX"; Pos = 32, MaxLv = 5, NeedSkillList = {12, 17, 18, 20}}},
	[4056] = {
		{"RA_AIMEDBOLT"; Pos = 0, MaxLv = 10, NeedSkillList = {}},
		{"RA_RESEARCHTRAP"; Pos = 1, MaxLv = 5, NeedSkillList = {}},
		{"RA_RANGERMAIN"; Pos = 3, MaxLv = 10, NeedSkillList = {}},
		{"RA_ELECTRICSHOCKER"; Pos = 4, MaxLv = 5, NeedSkillList = {}},
		{"RA_WUGMASTERY"; Pos = 5, MaxLv = 1, NeedSkillList = {}},
		{"RA_ARROWSTORM"; Pos = 7, MaxLv = 10, NeedSkillList = {0}},
		{"RA_CLUSTERBOMB"; Pos = 8, MaxLv = 5, NeedSkillList = {1}},
		{"RA_DETONATOR"; Pos = 9, MaxLv = 1, NeedSkillList = {8}},
		{"RA_CAMOUFLAGE"; Pos = 10, MaxLv = 5, NeedSkillList = {3}},
		{"RA_TOOTHOFWUG"; Pos = 12, MaxLv = 10, NeedSkillList = {5}},
		{"RA_WUGRIDER"; Pos = 13, MaxLv = 3, NeedSkillList = {5}},
		{"RA_FEARBREEZE"; Pos = 14, MaxLv = 5, NeedSkillList = {7, 10}},
		{"RA_MAGENTATRAP"; Pos = 15, MaxLv = 1, NeedSkillList = {1}},
		{"RA_FIRINGTRAP"; Pos = 16, MaxLv = 5, NeedSkillList = {9}},
		{"RA_ICEBOUNDTRAP"; Pos = 17, MaxLv = 5, NeedSkillList = {9}},
		{"RA_SENSITIVEKEEN"; Pos = 18, MaxLv = 5, NeedSkillList = {12}},
		{"RA_WUGSTRIKE"; Pos = 19, MaxLv = 5, NeedSkillList = {12}},
		{"RA_WUGDASH"; Pos = 20, MaxLv = 1, NeedSkillList = {13}},
		{"RA_COBALTTRAP"; Pos = 22, MaxLv = 1, NeedSkillList = {1}},
		{"RA_WUGBITE"; Pos = 26, MaxLv = 5, NeedSkillList = {19}},
		{"RA_MAIZETRAP"; Pos = 29, MaxLv = 1, NeedSkillList = {1}},
		{"RA_VERDURETRAP"; Pos = 36, MaxLv = 1, NeedSkillList = {1}}},
	[4057] = {
		{"AB_JUDEX"; Pos = 0, MaxLv = 5, NeedSkillList = {}},
		{"AB_CHEAL"; Pos = 1, MaxLv = 3, NeedSkillList = {}},
		{"AB_CLEMENTIA"; Pos = 2, MaxLv = 3, NeedSkillList = {}},
		{"AB_PRAEFATIO"; Pos = 3, MaxLv = 10, NeedSkillList = {}},
		{"AB_DUPLELIGHT"; Pos = 4, MaxLv = 10, NeedSkillList = {}},
		{"AB_LAUDAAGNUS"; Pos = 5, MaxLv = 4, NeedSkillList = {}},
		{"AB_CANTO"; Pos = 6, MaxLv = 3, NeedSkillList = {}},
		{"AB_RENOVATIO"; Pos = 8, MaxLv = 1, NeedSkillList = {1}},
		{"AB_ANCILLA"; Pos = 9, MaxLv = 1, NeedSkillList = {2}},
		{"AB_ORATIO"; Pos = 10, MaxLv = 10, NeedSkillList = {3}},
		{"AB_LAUDARAMUS"; Pos = 12, MaxLv = 4, NeedSkillList = {5}},
		{"AB_ADORAMUS"; Pos = 14, MaxLv = 10, NeedSkillList = {0, 9}},
		{"AB_HIGHNESSHEAL"; Pos = 15, MaxLv = 5, NeedSkillList = {8}},
		{"AB_EXPIATIO"; Pos = 18, MaxLv = 5, NeedSkillList = {4, 10}},
		{"AB_CLEARANCE"; Pos = 19, MaxLv = 5, NeedSkillList = {12}},
		{"AB_EPICLESIS"; Pos = 23, MaxLv = 5, NeedSkillList = {9, 15}},
		{"AB_SILENTIUM"; Pos = 26, MaxLv = 5, NeedSkillList = {19}},
		{"AB_EUCHARISTICA"; Pos = 30, MaxLv = 10, NeedSkillList = {18, 23}},
		{"AB_SECRAMENT"; Pos = 32, MaxLv = 5, NeedSkillList = {18, 23}}},
	[4058] = {
		{"NC_MADOLICENCE"; Pos = 2, MaxLv = 5, NeedSkillList = {}},
		{"NC_TRAININGAXE"; Pos = 5, MaxLv = 10, NeedSkillList = {}},
		{"NC_RESEARCHFE"; Pos = 6, MaxLv = 5, NeedSkillList = {}},
		{"NC_REPAIR"; Pos = 7, MaxLv = 5, NeedSkillList = {2}},
		{"NC_BOOSTKNUCKLE"; Pos = 8, MaxLv = 5, NeedSkillList = {2}},
		{"NC_ACCELERATION"; Pos = 9, MaxLv = 3, NeedSkillList = {2}},
		{"NC_MAINFRAME"; Pos = 10, MaxLv = 4, NeedSkillList = {2}},
		{"NC_AXETORNADO"; Pos = 11, MaxLv = 5, NeedSkillList = {5}},
		{"NC_AXEBOOMERANG"; Pos = 12, MaxLv = 5, NeedSkillList = {5}},
		{"NC_SILVERSNIPER"; Pos = 13, MaxLv = 5, NeedSkillList = {6}},
		{"NC_PILEBUNKER"; Pos = 14, MaxLv = 3, NeedSkillList = {8}},
		{"NC_VULCANARM"; Pos = 15, MaxLv = 3, NeedSkillList = {8}},
		{"NC_HOVERING"; Pos = 16, MaxLv = 1, NeedSkillList = {9}},
		{"NC_SHAPESHIFT"; Pos = 17, MaxLv = 4, NeedSkillList = {10}},
		{"NC_SELFDESTRUCTION"; Pos = 18, MaxLv = 3, NeedSkillList = {10}},
		{"NC_POWERSWING"; Pos = 19, MaxLv = 5, NeedSkillList = {12}},
		{"NC_FLAMELAUNCHER"; Pos = 21, MaxLv = 3, NeedSkillList = {15}},
		{"NC_COLDSLOWER"; Pos = 22, MaxLv = 3, NeedSkillList = {15}},
		{"NC_F_SIDESLIDE"; Pos = 23, MaxLv = 1, NeedSkillList = {16}},
		{"NC_INFRAREDSCAN"; Pos = 24, MaxLv = 1, NeedSkillList = {17}},
		{"NC_EMERGENCYCOOL"; Pos = 25, MaxLv = 1, NeedSkillList = {18}},
		{"NC_DISJOINT"; Pos = 26, MaxLv = 1, NeedSkillList = {13}},
		{"NC_MAGICDECOY"; Pos = 27, MaxLv = 5, NeedSkillList = {13}},
		{"NC_ARMSCANNON"; Pos = 29, MaxLv = 3, NeedSkillList = {21, 22}},
		{"NC_B_SIDESLIDE"; Pos = 30, MaxLv = 1, NeedSkillList = {16}},
		{"NC_ANALYZE"; Pos = 31, MaxLv = 3, NeedSkillList = {24}},
		{"NC_MAGNETICFIELD"; Pos = 32, MaxLv = 3, NeedSkillList = {25}},
		{"NC_NEUTRALBARRIER"; Pos = 39, MaxLv = 3, NeedSkillList = {32}},
		{"NC_STEALTHFIELD"; Pos = 40, MaxLv = 3, NeedSkillList = {31, 39}}},
	[4059] = {
		{"GC_CROSSIMPACT"; Pos = 0, MaxLv = 5, NeedSkillList = {}},
		{"GC_CLOAKINGEXCEED"; Pos = 1, MaxLv = 5, NeedSkillList = {}},
		{"GC_ROLLINGCUTTER"; Pos = 2, MaxLv = 5, NeedSkillList = {}},
		{"GC_WEAPONBLOCKING"; Pos = 3, MaxLv = 5, NeedSkillList = {}},
		{"GC_VENOMIMPRESS"; Pos = 4, MaxLv = 5, NeedSkillList = {}},
		{"GC_RESEARCHNEWPOISON"; Pos = 5, MaxLv = 10, NeedSkillList = {}},
		{"GC_DARKILLUSION"; Pos = 7, MaxLv = 5, NeedSkillList = {0}},
		{"GC_CROSSRIPPERSLASHER"; Pos = 9, MaxLv = 5, NeedSkillList = {2}},
		{"GC_WEAPONCRUSH"; Pos = 10, MaxLv = 5, NeedSkillList = {3}},
		{"GC_COUNTERSLASH"; Pos = 11, MaxLv = 5, NeedSkillList = {3}},
		{"GC_CREATENEWPOISON"; Pos = 12, MaxLv = 1, NeedSkillList = {5}},
		{"GC_ANTIDOTE"; Pos = 13, MaxLv = 1, NeedSkillList = {5}},
		{"GC_PHANTOMMENACE"; Pos = 15, MaxLv = 1, NeedSkillList = {1, 7}},
		{"GC_POISONINGWEAPON"; Pos = 19, MaxLv = 5, NeedSkillList = {12}},
		{"GC_HALLUCINATIONWALK"; Pos = 22, MaxLv = 5, NeedSkillList = {15}},
		{"GC_VENOMPRESSURE"; Pos = 25, MaxLv = 5, NeedSkillList = {3, 19}},
		{"GC_POISONSMOKE"; Pos = 26, MaxLv = 5, NeedSkillList = {19, 25}}},
	[4066] = {
		{"LG_MOONSLASHER"; Pos = 0, MaxLv = 5, NeedSkillList = {}},
		{"LG_BANISHINGPOINT"; Pos = 1, MaxLv = 10, NeedSkillList = {}},
		{"LG_FORCEOFVANGUARD"; Pos = 2, MaxLv = 5, NeedSkillList = {}},
		{"LG_TRAMPLE"; Pos = 3, MaxLv = 3, NeedSkillList = {}},
		{"LG_PIETY"; Pos = 4, MaxLv = 5, NeedSkillList = {}},
		{"LG_REFLECTDAMAGE"; Pos = 5, MaxLv = 5, NeedSkillList = {}},
		{"LG_SHIELDPRESS"; Pos = 6, MaxLv = 5, NeedSkillList = {}},
		{"LG_EXEEDBREAK"; Pos = 7, MaxLv = 5, NeedSkillList = {1}},
		{"LG_PINPOINTATTACK"; Pos = 8, MaxLv = 5, NeedSkillList = {1}},
		{"LG_RAGEBURST"; Pos = 9, MaxLv = 1, NeedSkillList = {2}},
		{"LG_PRESTIGE"; Pos = 10, MaxLv = 5, NeedSkillList = {3}},
		{"LG_RAYOFGENESIS"; Pos = 11, MaxLv = 5, NeedSkillList = {}},
		{"LG_EARTHDRIVE"; Pos = 12, MaxLv = 5, NeedSkillList = {5}},
		{"LG_CANNONSPEAR"; Pos = 14, MaxLv = 5, NeedSkillList = {8}},
		{"LG_OVERBRAND"; Pos = 15, MaxLv = 5, NeedSkillList = {0, 8}},
		{"LG_BANDING"; Pos = 16, MaxLv = 5, NeedSkillList = {8, 9}},
		{"LG_SHIELDSPELL"; Pos = 19, MaxLv = 3, NeedSkillList = {6, 12}},
		{"LG_HESPERUSLIT"; Pos = 24, MaxLv = 5, NeedSkillList = {10, 16}},
		{"LG_INSPIRATION"; Pos = 26, MaxLv = 5, NeedSkillList = {4, 11, 19}}},
	[4067] = {
		{"SO_FIREWALK"; Pos = 0, MaxLv = 5, NeedSkillList = {}},
		{"SO_ELECTRICWALK"; Pos = 1, MaxLv = 5, NeedSkillList = {}},
		{"SO_EARTHGRAVE"; Pos = 2, MaxLv = 5, NeedSkillList = {}},
		{"SO_DIAMONDDUST"; Pos = 3, MaxLv = 5, NeedSkillList = {}},
		{"SO_CLOUD_KILL"; Pos = 4, MaxLv = 5, NeedSkillList = {}},
		{"SO_SPELLFIST"; Pos = 5, MaxLv = 5, NeedSkillList = {}},
		{"SO_STRIKING"; Pos = 6, MaxLv = 5, NeedSkillList = {}},
		{"SO_WARMER"; Pos = 7, MaxLv = 5, NeedSkillList = {}},
		{"SO_VARETYR_SPEAR"; Pos = 8, MaxLv = 5, NeedSkillList = {}},
		{"SO_VACUUM_EXTREME"; Pos = 9, MaxLv = 5, NeedSkillList = {}},
		{"SO_POISON_BUSTER"; Pos = 11, MaxLv = 5, NeedSkillList = {4}},
		{"SO_PSYCHIC_WAVE"; Pos = 12, MaxLv = 5, NeedSkillList = {}},
		{"SO_ARRULLO"; Pos = 14, MaxLv = 5, NeedSkillList = {7}}},
	[4068] = {
		{"WM_SEVERE_RAINSTORM"; Pos = 0, MaxLv = 5, NeedSkillList = {}},
		{"WM_REVERBERATION"; Pos = 1, MaxLv = 5, NeedSkillList = {}},
		{"WM_LESSON"; Pos = 3, MaxLv = 10, NeedSkillList = {}},
		{"WM_DOMINION_IMPULSE"; Pos = 8, MaxLv = 1, NeedSkillList = {1}},
		{"WM_SIRCLEOFNATURE"; Pos = 9, MaxLv = 5, NeedSkillList = {3}},
		{"WM_LULLABY_DEEPSLEEP"; Pos = 10, MaxLv = 5, NeedSkillList = {3}},
		{"WM_POEMOFNETHERWORLD"; Pos = 11, MaxLv = 5, NeedSkillList = {3}},
		{"WM_METALICSOUND"; Pos = 15, MaxLv = 5, NeedSkillList = {8}},
		{"WM_DEADHILLHERE"; Pos = 16, MaxLv = 5, NeedSkillList = {9}},
		{"WM_VOICEOFSIREN"; Pos = 18, MaxLv = 5, NeedSkillList = {11}},
		{"WM_RANDOMIZESPELL"; Pos = 19, MaxLv = 5, NeedSkillList = {11}},
		{"WM_GREAT_ECHO"; Pos = 22, MaxLv = 5, NeedSkillList = {15}},
		{"MI_HARMONIZE"; Pos = 23, MaxLv = 5, NeedSkillList = {10}},
		{"MI_RUSH_WINDMILL"; Pos = 24, MaxLv = 5, NeedSkillList = {10}},
		{"MI_ECHOSONG"; Pos = 25, MaxLv = 5, NeedSkillList = {10}},
		{"WM_GLOOMYDAY"; Pos = 26, MaxLv = 5, NeedSkillList = {19}},
		{"WM_DANCE_WITH_WUG"; Pos = 30, MaxLv = 5, NeedSkillList = {23, 24, 25}},
		{"WM_SONG_OF_MANA"; Pos = 31, MaxLv = 5, NeedSkillList = {23, 24, 25}},
		{"WM_LERADS_DEW"; Pos = 32, MaxLv = 5, NeedSkillList = {23, 24, 25}},
		{"WM_SATURDAY_NIGHT_FEVER"; Pos = 37, MaxLv = 5, NeedSkillList = {30}},
		{"WM_MELODYOFSINK"; Pos = 38, MaxLv = 5, NeedSkillList = {31}},
		{"WM_BEYOND_OF_WARCRY"; Pos = 39, MaxLv = 5, NeedSkillList = {32}},
		{"WM_SOUND_OF_DESTRUCTION"; Pos = 45, MaxLv = 5, NeedSkillList = {37, 38}},
		{"WM_UNLIMITED_HUMMING_VOICE"; Pos = 46, MaxLv = 5, NeedSkillList = {39, 45}}},	
	[4069] = {
		{"WM_SEVERE_RAINSTORM"; Pos = 0, MaxLv = 5, NeedSkillList = {}},
		{"WM_REVERBERATION"; Pos = 1, MaxLv = 5, NeedSkillList = {}},
		{"WM_LESSON"; Pos = 3, MaxLv = 10, NeedSkillList = {}},
		{"WM_DOMINION_IMPULSE"; Pos = 8, MaxLv = 1, NeedSkillList = {1}},
		{"WM_SIRCLEOFNATURE"; Pos = 9, MaxLv = 5, NeedSkillList = {3}},
		{"WM_LULLABY_DEEPSLEEP"; Pos = 10, MaxLv = 5, NeedSkillList = {3}},
		{"WM_POEMOFNETHERWORLD"; Pos = 11, MaxLv = 5, NeedSkillList = {3}},
		{"WM_METALICSOUND"; Pos = 15, MaxLv = 5, NeedSkillList = {8}},
		{"WM_DEADHILLHERE"; Pos = 16, MaxLv = 5, NeedSkillList = {9}},
		{"WM_VOICEOFSIREN"; Pos = 18, MaxLv = 5, NeedSkillList = {11}},
		{"WM_RANDOMIZESPELL"; Pos = 19, MaxLv = 5, NeedSkillList = {11}},
		{"WM_GREAT_ECHO"; Pos = 22, MaxLv = 5, NeedSkillList = {15}},
		{"WA_SWING_DANCE"; Pos = 23, MaxLv = 5, NeedSkillList = {10}},
		{"WA_SYMPHONY_OF_LOVER"; Pos = 24, MaxLv = 5, NeedSkillList = {10}},
		{"WA_MOONLIT_SERENADE"; Pos = 25, MaxLv = 5, NeedSkillList = {10}},
		{"WM_GLOOMYDAY"; Pos = 26, MaxLv = 5, NeedSkillList = {19}},
		{"WM_DANCE_WITH_WUG"; Pos = 30, MaxLv = 5, NeedSkillList = {23, 24, 25}},
		{"WM_SONG_OF_MANA"; Pos = 31, MaxLv = 5, NeedSkillList = {23, 24, 25}},
		{"WM_LERADS_DEW"; Pos = 32, MaxLv = 5, NeedSkillList = {23, 24, 25}},
		{"WM_SATURDAY_NIGHT_FEVER"; Pos = 37, MaxLv = 5, NeedSkillList = {30}},
		{"WM_MELODYOFSINK"; Pos = 38, MaxLv = 5, NeedSkillList = {31}},
		{"WM_BEYOND_OF_WARCRY"; Pos = 39, MaxLv = 5, NeedSkillList = {32}},
		{"WM_SOUND_OF_DESTRUCTION"; Pos = 45, MaxLv = 5, NeedSkillList = {37, 38}},
		{"WM_UNLIMITED_HUMMING_VOICE"; Pos = 46, MaxLv = 5, NeedSkillList = {39, 45}}},
	[4070] = {
		{"SR_POWERVELOCITY"; Pos = 0, MaxLv = 1, NeedSkillList = {}},
		{"SR_RIDEINLIGHTNING"; Pos = 1, MaxLv = 5, NeedSkillList = {}},
		{"SR_DRAGONCOMBO"; Pos = 2, MaxLv = 10, NeedSkillList = {}},
		{"SR_ASSIMILATEPOWER"; Pos = 7, MaxLv = 1, NeedSkillList = {0}},
		{"SR_SKYNETBLOW"; Pos = 8, MaxLv = 5, NeedSkillList = {2}},
		{"SR_FALLENEMPIRE"; Pos = 9, MaxLv = 5, NeedSkillList = {2}},
		{"SR_GENTLETOUCH_QUIET"; Pos = 11, MaxLv = 5, NeedSkillList = {0}},
		{"SR_GENTLETOUCH_CURE"; Pos = 12, MaxLv = 5, NeedSkillList = {0}},
		{"SR_HOWLINGOFLION"; Pos = 14, MaxLv = 5, NeedSkillList = {1, 7}},
		{"SR_CRESCENTELBOW"; Pos = 15, MaxLv = 5, NeedSkillList = {8}},
		{"SR_TIGERCANNON"; Pos = 16, MaxLv = 10, NeedSkillList = {9}},
		{"SR_CURSEDCIRCLE"; Pos = 17, MaxLv = 5, NeedSkillList = {11}},
		{"SR_GENTLETOUCH_ENERGYGAIN"; Pos = 18, MaxLv = 5, NeedSkillList = {11}},
		{"SR_GENTLETOUCH_CHANGE"; Pos = 19, MaxLv = 5, NeedSkillList = {12}},
		{"SR_WINDMILL"; Pos = 24, MaxLv = 1, NeedSkillList = {17}},
		{"SR_EARTHSHAKER"; Pos = 25, MaxLv = 5, NeedSkillList = {2, 17}},
		{"SR_GENTLETOUCH_REVITALIZE"; Pos = 26, MaxLv = 5, NeedSkillList = {19}},
		{"SR_LIGHTNINGWALK"; Pos = 31, MaxLv = 5, NeedSkillList = {24}},
		{"SR_RAMPAGEBLASTER"; Pos = 32, MaxLv = 5, NeedSkillList = {25}},
		{"SR_KNUCKLEARROW"; Pos = 38, MaxLv = 5, NeedSkillList = {31, 32}},
		{"SR_RAISINGDRAGON"; Pos = 39, MaxLv = 10, NeedSkillList = {32, 18}},
		{"SR_GATEOFHELL"; Pos = 36, MaxLv = 10, NeedSkillList = {16, 39}}},
	[4071] = {
		{"GN_CHANGEMATERIAL"; Pos = 0, MaxLv = 1, NeedSkillList = {}},
		{"GN_TRAINING_SWORD"; Pos = 1, MaxLv = 5, NeedSkillList = {}},
		{"GN_S_PHARMACY"; Pos = 2, MaxLv = 10, NeedSkillList = {}},
		{"GN_REMODELING_CART"; Pos = 5, MaxLv = 5, NeedSkillList = {}},
		{"GN_SLINGITEM"; Pos = 7, MaxLv = 1, NeedSkillList = {0}},
		{"GN_MIX_COOKING"; Pos = 8, MaxLv = 2, NeedSkillList = {2}},
		{"GN_THORNS_TRAP"; Pos = 9, MaxLv = 5, NeedSkillList = {2}},
		{"GN_BLOOD_SUCKER"; Pos = 10, MaxLv = 5, NeedSkillList = {2}},
		{"GN_SPORE_EXPLOSION"; Pos = 11, MaxLv = 5, NeedSkillList = {2}},
		{"GN_CART_TORNADO"; Pos = 12, MaxLv = 5, NeedSkillList = {5}},
		{"GN_MAKEBOMB"; Pos = 15, MaxLv = 2, NeedSkillList = {8}},
		{"GN_WALLOFTHORN"; Pos = 16, MaxLv = 5, NeedSkillList = {9}},
		{"GN_HELLS_PLANT"; Pos = 17, MaxLv = 5, NeedSkillList = {10}},
		{"GN_DEMONIC_FIRE"; Pos = 18, MaxLv = 5, NeedSkillList = {11}},
		{"GN_CARTCANNON"; Pos = 19, MaxLv = 5, NeedSkillList = {5}},
		{"GN_CRAZYWEED"; Pos = 23, MaxLv = 10, NeedSkillList = {16}},
		{"GN_MANDRAGORA"; Pos = 24, MaxLv = 5, NeedSkillList = {17}},
		{"GN_FIRE_EXPANSION"; Pos = 25, MaxLv = 5, NeedSkillList = {18}},
		{"GN_CARTBOOST"; Pos = 26, MaxLv = 5, NeedSkillList = {5}}},
	[4072] = {
		{"SC_REPRODUCE"; Pos = 0, MaxLv = 10, NeedSkillList = {}},
		{"SC_SHADOWFORM"; Pos = 1, MaxLv = 5, NeedSkillList = {}},
		{"SC_FATALMENACE"; Pos = 2, MaxLv = 5, NeedSkillList = {}},
		{"SC_BODYPAINT"; Pos = 3, MaxLv = 5, NeedSkillList = {}},
		{"SC_TRIANGLESHOT"; Pos = 4, MaxLv = 10, NeedSkillList = {}},
		{"SC_MANHOLE"; Pos = 5, MaxLv = 3, NeedSkillList = {}},
		{"SC_STRIPACCESSARY"; Pos = 6, MaxLv = 5, NeedSkillList = {}},
		{"SC_AUTOSHADOWSPELL"; Pos = 7, MaxLv = 10, NeedSkillList = {0}},
		{"SC_ENERVATION"; Pos = 9, MaxLv = 3, NeedSkillList = {3}},
		{"SC_GROOMY"; Pos = 10, MaxLv = 3, NeedSkillList = {3}},
		{"SC_IGNORANCE"; Pos = 11, MaxLv = 3, NeedSkillList = {3}},
		{"SC_CHAOSPANIC"; Pos = 12, MaxLv = 3, NeedSkillList = {5}},
		{"SC_DIMENSIONDOOR"; Pos = 13, MaxLv = 3, NeedSkillList = {5}},
		{"SC_DEADLYINFECT"; Pos = 15, MaxLv = 5, NeedSkillList = {1}},
		{"SC_LAZINESS"; Pos = 16, MaxLv = 3, NeedSkillList = {9, 10, 11}},
		{"SC_WEAKNESS"; Pos = 17, MaxLv = 3, NeedSkillList = {9, 10, 11}},
		{"SC_FEINTBOMB"; Pos = 19, MaxLv = 3, NeedSkillList = {13}},
		{"SC_BLOODYLUST"; Pos = 20, MaxLv = 3, NeedSkillList = {13}},
		{"SC_UNLUCKY"; Pos = 24, MaxLv = 3, NeedSkillList = {16, 17}},
		{"SC_INVISIBILITY"; Pos = 29, MaxLv = 5, NeedSkillList = {24, 7, 15}},
		{"SC_MAELSTROM"; Pos = 33, MaxLv = 3, NeedSkillList = {12, 24}}},
	[5] = {
		{"MC_INCCARRY"; Pos = 1, MaxLv = 10, NeedSkillList = {}},
		{"MC_MAMMONITE"; Pos = 3, MaxLv = 10, NeedSkillList = {}},
		{"MC_IDENTIFY"; Pos = 4, MaxLv = 1, NeedSkillList = {}},
		{"MC_LOUD"; Pos = 5, MaxLv = 1, NeedSkillList = {}},
		{"MC_DISCOUNT"; Pos = 8, MaxLv = 10, NeedSkillList = {1}},
		{"MC_PUSHCART"; Pos = 9, MaxLv = 10, NeedSkillList = {1}},
		{"MC_CHANGECART"; Pos = 12, MaxLv = 1, NeedSkillList = {}},
		{"MC_OVERCHARGE"; Pos = 15, MaxLv = 10, NeedSkillList = {8}},
		{"MC_VENDING"; Pos = 16, MaxLv = 10, NeedSkillList = {9}},
		{"MC_CARTREVOLUTION"; Pos = 19, MaxLv = 1, NeedSkillList = {}}},
	[6] = {
		{"TF_DOUBLE"; Pos = 1, MaxLv = 10, NeedSkillList = {}},
		{"TF_STEAL"; Pos = 2, MaxLv = 10, NeedSkillList = {}},
		{"TF_POISON"; Pos = 3, MaxLv = 10, NeedSkillList = {}},
		{"TF_SPRINKLESAND"; Pos = 4, MaxLv = 1, NeedSkillList = {}},
		{"TF_THROWSTONE"; Pos = 5, MaxLv = 1, NeedSkillList = {}},
		{"TF_MISS"; Pos = 8, MaxLv = 10, NeedSkillList = {}},
		{"TF_HIDING"; Pos = 9, MaxLv = 10, NeedSkillList = {2}},
		{"TF_DETOXIFY"; Pos = 10, MaxLv = 1, NeedSkillList = {3}},
		{"TF_BACKSLIDING"; Pos = 11, MaxLv = 1, NeedSkillList = {}},
		{"TF_PICKSTONE"; Pos = 12, MaxLv = 1, NeedSkillList = {}}},
	[7] = {
		{"KN_TWOHANDQUICKEN"; Pos = 0, MaxLv = 10, NeedSkillList = {}},
		{"KN_AUTOCOUNTER"; Pos = 1, MaxLv = 5, NeedSkillList = {}},
		{"KN_RIDING"; Pos = 2, MaxLv = 1, NeedSkillList = {}},
		{"KN_SPEARMASTERY"; Pos = 3, MaxLv = 10, NeedSkillList = {}},
		{"KN_CHARGEATK"; Pos = 6, MaxLv = 1, NeedSkillList = {}},
		{"KN_BOWLINGBASH"; Pos = 8, MaxLv = 10, NeedSkillList = {0, 1}},
		{"KN_CAVALIERMASTERY"; Pos = 9, MaxLv = 5, NeedSkillList = {2}},
		{"KN_PIERCE"; Pos = 10, MaxLv = 10, NeedSkillList = {3}},
		{"KN_ONEHAND"; Pos = 13, MaxLv = 1, NeedSkillList = {}},
		{"KN_SPEARBOOMERANG"; Pos = 16, MaxLv = 5, NeedSkillList = {10}},
		{"KN_SPEARSTAB"; Pos = 17, MaxLv = 10, NeedSkillList = {10}},
		{"KN_BRANDISHSPEAR"; Pos = 24, MaxLv = 10, NeedSkillList = {2, 17}}},
	[8] = {
		{"PR_KYRIE"; Pos = 0, MaxLv = 10, NeedSkillList = {}},
		{"PR_MAGNIFICAT"; Pos = 1, MaxLv = 5, NeedSkillList = {}},
		{"PR_STRECOVERY"; Pos = 2, MaxLv = 1, NeedSkillList = {}},
		{"MG_SRECOVERY"; Pos = 3, MaxLv = 10, NeedSkillList = {}},
		{"PR_LEXDIVINA"; Pos = 4, MaxLv = 10, NeedSkillList = {}},
		{"PR_IMPOSITIO"; Pos = 5, MaxLv = 5, NeedSkillList = {}},
		{"PR_SANCTUARY"; Pos = 6, MaxLv = 10, NeedSkillList = {}},
		{"PR_GLORIA"; Pos = 7, MaxLv = 5, NeedSkillList = {0, 1}},
		{"PR_SLOWPOISON"; Pos = 8, MaxLv = 4, NeedSkillList = {}},
		{"ALL_RESURRECTION"; Pos = 9, MaxLv = 4, NeedSkillList = {3, 2}},
		{"PR_LEXAETERNA"; Pos = 11, MaxLv = 1, NeedSkillList = {4}},
		{"PR_SUFFRAGIUM"; Pos = 12, MaxLv = 3, NeedSkillList = {5}},
		{"PR_ASPERSIO"; Pos = 13, MaxLv = 5, NeedSkillList = {5}},
		{"PR_BENEDICTIO"; Pos = 14, MaxLv = 5, NeedSkillList = {13, 7}},
		{"PR_MACEMASTERY"; Pos = 15, MaxLv = 10, NeedSkillList = {}},
		{"PR_TURNUNDEAD"; Pos = 16, MaxLv = 10, NeedSkillList = {9, 4}},
		{"MG_SAFETYWALL"; Pos = 20, MaxLv = 10, NeedSkillList = {6, 13}},
		{"PR_MAGNUS"; Pos = 25, MaxLv = 10, NeedSkillList = {20, 11, 16}},
		{"PR_REDEMPTIO"; Pos = 27, MaxLv = 1, NeedSkillList = {}}},	
	[9] = {
		{"WZ_ESTIMATION"; Pos = 0, MaxLv = 1, NeedSkillList = {}},
		{"WZ_ICEWALL"; Pos = 1, MaxLv = 10, NeedSkillList = {}},
		{"WZ_JUPITEL"; Pos = 2, MaxLv = 10, NeedSkillList = {}},
		{"WZ_EARTHSPIKE"; Pos = 3, MaxLv = 5, NeedSkillList = {}},
		{"WZ_SIGHTRASHER"; Pos = 4, MaxLv = 10, NeedSkillList = {}},
		{"WZ_FIREPILLAR"; Pos = 5, MaxLv = 10, NeedSkillList = {}},
		{"WZ_SIGHTBLASTER"; Pos = 6, MaxLv = 1, NeedSkillList = {}},
		{"WZ_FROSTNOVA"; Pos = 8, MaxLv = 10, NeedSkillList = {1}},
		{"WZ_VERMILION"; Pos = 9, MaxLv = 10, NeedSkillList = {2}},
		{"WZ_HEAVENDRIVE"; Pos = 10, MaxLv = 5, NeedSkillList = {3}},
		{"WZ_METEOR"; Pos = 11, MaxLv = 10, NeedSkillList = {4}},
		{"WZ_WATERBALL"; Pos = 15, MaxLv = 5, NeedSkillList = {}},
		{"WZ_QUAGMIRE"; Pos = 17, MaxLv = 5, NeedSkillList = {10}},
		{"WZ_STORMGUST"; Pos = 22, MaxLv = 10, NeedSkillList = {2}}},
	["__newindex"] = function () error("unknown state") end
}
setmetatable(NEED_SKILLLIST_FOR_JOB, NEED_SKILLLIST_FOR_JOB)